/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as C4RouteImport } from './routes/c4'
import { Route as C3RouteImport } from './routes/c3'
import { Route as C2RouteImport } from './routes/c2'
import { Route as C1RouteImport } from './routes/c1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as C4IndexRouteImport } from './routes/c4.index'
import { Route as C3IndexRouteImport } from './routes/c3.index'
import { Route as C2IndexRouteImport } from './routes/c2.index'
import { Route as C1IndexRouteImport } from './routes/c1.index'
import { Route as C4WarehousesRouteImport } from './routes/c4.warehouses'
import { Route as C4VerticalsRouteImport } from './routes/c4.verticals'
import { Route as C4TeamRouteImport } from './routes/c4.team'
import { Route as C4OfficesRouteImport } from './routes/c4.offices'
import { Route as C4NewsRouteImport } from './routes/c4.news'
import { Route as C4NetworkRouteImport } from './routes/c4.network'
import { Route as C4JourneyRouteImport } from './routes/c4.journey'
import { Route as C4EventsRouteImport } from './routes/c4.events'
import { Route as C4ContactRouteImport } from './routes/c4.contact'
import { Route as C4AboutRouteImport } from './routes/c4.about'
import { Route as C3WarehousesRouteImport } from './routes/c3.warehouses'
import { Route as C3VerticalsRouteImport } from './routes/c3.verticals'
import { Route as C3TeamRouteImport } from './routes/c3.team'
import { Route as C3OfficesRouteImport } from './routes/c3.offices'
import { Route as C3NewsRouteImport } from './routes/c3.news'
import { Route as C3NetworkRouteImport } from './routes/c3.network'
import { Route as C3JourneyRouteImport } from './routes/c3.journey'
import { Route as C3EventsRouteImport } from './routes/c3.events'
import { Route as C3ContactRouteImport } from './routes/c3.contact'
import { Route as C3AboutRouteImport } from './routes/c3.about'
import { Route as C2WarehousesRouteImport } from './routes/c2.warehouses'
import { Route as C2VerticalsRouteImport } from './routes/c2.verticals'
import { Route as C2TeamRouteImport } from './routes/c2.team'
import { Route as C2OfficesRouteImport } from './routes/c2.offices'
import { Route as C2NewsRouteImport } from './routes/c2.news'
import { Route as C2NetworkRouteImport } from './routes/c2.network'
import { Route as C2JourneyRouteImport } from './routes/c2.journey'
import { Route as C2EventsRouteImport } from './routes/c2.events'
import { Route as C2ContactRouteImport } from './routes/c2.contact'
import { Route as C2AboutRouteImport } from './routes/c2.about'
import { Route as C1WarehousesRouteImport } from './routes/c1.warehouses'
import { Route as C1VerticalsRouteImport } from './routes/c1.verticals'
import { Route as C1TeamRouteImport } from './routes/c1.team'
import { Route as C1OfficesRouteImport } from './routes/c1.offices'
import { Route as C1NewsRouteImport } from './routes/c1.news'
import { Route as C1NetworkRouteImport } from './routes/c1.network'
import { Route as C1JourneyRouteImport } from './routes/c1.journey'
import { Route as C1EventsRouteImport } from './routes/c1.events'
import { Route as C1ContactRouteImport } from './routes/c1.contact'
import { Route as C1AboutRouteImport } from './routes/c1.about'
import { Route as C4NewsSlugRouteImport } from './routes/c4.news.$slug'
import { Route as C4EventsSlugRouteImport } from './routes/c4.events.$slug'
import { Route as C3VerticalsSlugRouteImport } from './routes/c3.verticals.$slug'
import { Route as C3NewsSlugRouteImport } from './routes/c3.news.$slug'
import { Route as C3EventsSlugRouteImport } from './routes/c3.events.$slug'
import { Route as C2NewsSlugRouteImport } from './routes/c2.news.$slug'
import { Route as C2EventsSlugRouteImport } from './routes/c2.events.$slug'
import { Route as C1NewsSlugRouteImport } from './routes/c1.news.$slug'
import { Route as C1EventsSlugRouteImport } from './routes/c1.events.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const C4Route = C4RouteImport.update({
  id: '/c4',
  path: '/c4',
  getParentRoute: () => rootRouteImport,
} as any)
const C3Route = C3RouteImport.update({
  id: '/c3',
  path: '/c3',
  getParentRoute: () => rootRouteImport,
} as any)
const C2Route = C2RouteImport.update({
  id: '/c2',
  path: '/c2',
  getParentRoute: () => rootRouteImport,
} as any)
const C1Route = C1RouteImport.update({
  id: '/c1',
  path: '/c1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const C4IndexRoute = C4IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => C4Route,
} as any)
const C3IndexRoute = C3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => C3Route,
} as any)
const C2IndexRoute = C2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => C2Route,
} as any)
const C1IndexRoute = C1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => C1Route,
} as any)
const C4WarehousesRoute = C4WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => C4Route,
} as any)
const C4VerticalsRoute = C4VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => C4Route,
} as any)
const C4TeamRoute = C4TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => C4Route,
} as any)
const C4OfficesRoute = C4OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => C4Route,
} as any)
const C4NewsRoute = C4NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => C4Route,
} as any)
const C4NetworkRoute = C4NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => C4Route,
} as any)
const C4JourneyRoute = C4JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => C4Route,
} as any)
const C4EventsRoute = C4EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => C4Route,
} as any)
const C4ContactRoute = C4ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => C4Route,
} as any)
const C4AboutRoute = C4AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => C4Route,
} as any)
const C3WarehousesRoute = C3WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => C3Route,
} as any)
const C3VerticalsRoute = C3VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => C3Route,
} as any)
const C3TeamRoute = C3TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => C3Route,
} as any)
const C3OfficesRoute = C3OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => C3Route,
} as any)
const C3NewsRoute = C3NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => C3Route,
} as any)
const C3NetworkRoute = C3NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => C3Route,
} as any)
const C3JourneyRoute = C3JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => C3Route,
} as any)
const C3EventsRoute = C3EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => C3Route,
} as any)
const C3ContactRoute = C3ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => C3Route,
} as any)
const C3AboutRoute = C3AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => C3Route,
} as any)
const C2WarehousesRoute = C2WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => C2Route,
} as any)
const C2VerticalsRoute = C2VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => C2Route,
} as any)
const C2TeamRoute = C2TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => C2Route,
} as any)
const C2OfficesRoute = C2OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => C2Route,
} as any)
const C2NewsRoute = C2NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => C2Route,
} as any)
const C2NetworkRoute = C2NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => C2Route,
} as any)
const C2JourneyRoute = C2JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => C2Route,
} as any)
const C2EventsRoute = C2EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => C2Route,
} as any)
const C2ContactRoute = C2ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => C2Route,
} as any)
const C2AboutRoute = C2AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => C2Route,
} as any)
const C1WarehousesRoute = C1WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => C1Route,
} as any)
const C1VerticalsRoute = C1VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => C1Route,
} as any)
const C1TeamRoute = C1TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => C1Route,
} as any)
const C1OfficesRoute = C1OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => C1Route,
} as any)
const C1NewsRoute = C1NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => C1Route,
} as any)
const C1NetworkRoute = C1NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => C1Route,
} as any)
const C1JourneyRoute = C1JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => C1Route,
} as any)
const C1EventsRoute = C1EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => C1Route,
} as any)
const C1ContactRoute = C1ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => C1Route,
} as any)
const C1AboutRoute = C1AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => C1Route,
} as any)
const C4NewsSlugRoute = C4NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C4NewsRoute,
} as any)
const C4EventsSlugRoute = C4EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C4EventsRoute,
} as any)
const C3VerticalsSlugRoute = C3VerticalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C3VerticalsRoute,
} as any)
const C3NewsSlugRoute = C3NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C3NewsRoute,
} as any)
const C3EventsSlugRoute = C3EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C3EventsRoute,
} as any)
const C2NewsSlugRoute = C2NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C2NewsRoute,
} as any)
const C2EventsSlugRoute = C2EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C2EventsRoute,
} as any)
const C1NewsSlugRoute = C1NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C1NewsRoute,
} as any)
const C1EventsSlugRoute = C1EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => C1EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c1': typeof C1RouteWithChildren
  '/c2': typeof C2RouteWithChildren
  '/c3': typeof C3RouteWithChildren
  '/c4': typeof C4RouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c1/about': typeof C1AboutRoute
  '/c1/contact': typeof C1ContactRoute
  '/c1/events': typeof C1EventsRouteWithChildren
  '/c1/journey': typeof C1JourneyRoute
  '/c1/network': typeof C1NetworkRoute
  '/c1/news': typeof C1NewsRouteWithChildren
  '/c1/offices': typeof C1OfficesRoute
  '/c1/team': typeof C1TeamRoute
  '/c1/verticals': typeof C1VerticalsRoute
  '/c1/warehouses': typeof C1WarehousesRoute
  '/c2/about': typeof C2AboutRoute
  '/c2/contact': typeof C2ContactRoute
  '/c2/events': typeof C2EventsRouteWithChildren
  '/c2/journey': typeof C2JourneyRoute
  '/c2/network': typeof C2NetworkRoute
  '/c2/news': typeof C2NewsRouteWithChildren
  '/c2/offices': typeof C2OfficesRoute
  '/c2/team': typeof C2TeamRoute
  '/c2/verticals': typeof C2VerticalsRoute
  '/c2/warehouses': typeof C2WarehousesRoute
  '/c3/about': typeof C3AboutRoute
  '/c3/contact': typeof C3ContactRoute
  '/c3/events': typeof C3EventsRouteWithChildren
  '/c3/journey': typeof C3JourneyRoute
  '/c3/network': typeof C3NetworkRoute
  '/c3/news': typeof C3NewsRouteWithChildren
  '/c3/offices': typeof C3OfficesRoute
  '/c3/team': typeof C3TeamRoute
  '/c3/verticals': typeof C3VerticalsRouteWithChildren
  '/c3/warehouses': typeof C3WarehousesRoute
  '/c4/about': typeof C4AboutRoute
  '/c4/contact': typeof C4ContactRoute
  '/c4/events': typeof C4EventsRouteWithChildren
  '/c4/journey': typeof C4JourneyRoute
  '/c4/network': typeof C4NetworkRoute
  '/c4/news': typeof C4NewsRouteWithChildren
  '/c4/offices': typeof C4OfficesRoute
  '/c4/team': typeof C4TeamRoute
  '/c4/verticals': typeof C4VerticalsRoute
  '/c4/warehouses': typeof C4WarehousesRoute
  '/c1/': typeof C1IndexRoute
  '/c2/': typeof C2IndexRoute
  '/c3/': typeof C3IndexRoute
  '/c4/': typeof C4IndexRoute
  '/c1/events/$slug': typeof C1EventsSlugRoute
  '/c1/news/$slug': typeof C1NewsSlugRoute
  '/c2/events/$slug': typeof C2EventsSlugRoute
  '/c2/news/$slug': typeof C2NewsSlugRoute
  '/c3/events/$slug': typeof C3EventsSlugRoute
  '/c3/news/$slug': typeof C3NewsSlugRoute
  '/c3/verticals/$slug': typeof C3VerticalsSlugRoute
  '/c4/events/$slug': typeof C4EventsSlugRoute
  '/c4/news/$slug': typeof C4NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c1/about': typeof C1AboutRoute
  '/c1/contact': typeof C1ContactRoute
  '/c1/events': typeof C1EventsRouteWithChildren
  '/c1/journey': typeof C1JourneyRoute
  '/c1/network': typeof C1NetworkRoute
  '/c1/news': typeof C1NewsRouteWithChildren
  '/c1/offices': typeof C1OfficesRoute
  '/c1/team': typeof C1TeamRoute
  '/c1/verticals': typeof C1VerticalsRoute
  '/c1/warehouses': typeof C1WarehousesRoute
  '/c2/about': typeof C2AboutRoute
  '/c2/contact': typeof C2ContactRoute
  '/c2/events': typeof C2EventsRouteWithChildren
  '/c2/journey': typeof C2JourneyRoute
  '/c2/network': typeof C2NetworkRoute
  '/c2/news': typeof C2NewsRouteWithChildren
  '/c2/offices': typeof C2OfficesRoute
  '/c2/team': typeof C2TeamRoute
  '/c2/verticals': typeof C2VerticalsRoute
  '/c2/warehouses': typeof C2WarehousesRoute
  '/c3/about': typeof C3AboutRoute
  '/c3/contact': typeof C3ContactRoute
  '/c3/events': typeof C3EventsRouteWithChildren
  '/c3/journey': typeof C3JourneyRoute
  '/c3/network': typeof C3NetworkRoute
  '/c3/news': typeof C3NewsRouteWithChildren
  '/c3/offices': typeof C3OfficesRoute
  '/c3/team': typeof C3TeamRoute
  '/c3/verticals': typeof C3VerticalsRouteWithChildren
  '/c3/warehouses': typeof C3WarehousesRoute
  '/c4/about': typeof C4AboutRoute
  '/c4/contact': typeof C4ContactRoute
  '/c4/events': typeof C4EventsRouteWithChildren
  '/c4/journey': typeof C4JourneyRoute
  '/c4/network': typeof C4NetworkRoute
  '/c4/news': typeof C4NewsRouteWithChildren
  '/c4/offices': typeof C4OfficesRoute
  '/c4/team': typeof C4TeamRoute
  '/c4/verticals': typeof C4VerticalsRoute
  '/c4/warehouses': typeof C4WarehousesRoute
  '/c1': typeof C1IndexRoute
  '/c2': typeof C2IndexRoute
  '/c3': typeof C3IndexRoute
  '/c4': typeof C4IndexRoute
  '/c1/events/$slug': typeof C1EventsSlugRoute
  '/c1/news/$slug': typeof C1NewsSlugRoute
  '/c2/events/$slug': typeof C2EventsSlugRoute
  '/c2/news/$slug': typeof C2NewsSlugRoute
  '/c3/events/$slug': typeof C3EventsSlugRoute
  '/c3/news/$slug': typeof C3NewsSlugRoute
  '/c3/verticals/$slug': typeof C3VerticalsSlugRoute
  '/c4/events/$slug': typeof C4EventsSlugRoute
  '/c4/news/$slug': typeof C4NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c1': typeof C1RouteWithChildren
  '/c2': typeof C2RouteWithChildren
  '/c3': typeof C3RouteWithChildren
  '/c4': typeof C4RouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c1/about': typeof C1AboutRoute
  '/c1/contact': typeof C1ContactRoute
  '/c1/events': typeof C1EventsRouteWithChildren
  '/c1/journey': typeof C1JourneyRoute
  '/c1/network': typeof C1NetworkRoute
  '/c1/news': typeof C1NewsRouteWithChildren
  '/c1/offices': typeof C1OfficesRoute
  '/c1/team': typeof C1TeamRoute
  '/c1/verticals': typeof C1VerticalsRoute
  '/c1/warehouses': typeof C1WarehousesRoute
  '/c2/about': typeof C2AboutRoute
  '/c2/contact': typeof C2ContactRoute
  '/c2/events': typeof C2EventsRouteWithChildren
  '/c2/journey': typeof C2JourneyRoute
  '/c2/network': typeof C2NetworkRoute
  '/c2/news': typeof C2NewsRouteWithChildren
  '/c2/offices': typeof C2OfficesRoute
  '/c2/team': typeof C2TeamRoute
  '/c2/verticals': typeof C2VerticalsRoute
  '/c2/warehouses': typeof C2WarehousesRoute
  '/c3/about': typeof C3AboutRoute
  '/c3/contact': typeof C3ContactRoute
  '/c3/events': typeof C3EventsRouteWithChildren
  '/c3/journey': typeof C3JourneyRoute
  '/c3/network': typeof C3NetworkRoute
  '/c3/news': typeof C3NewsRouteWithChildren
  '/c3/offices': typeof C3OfficesRoute
  '/c3/team': typeof C3TeamRoute
  '/c3/verticals': typeof C3VerticalsRouteWithChildren
  '/c3/warehouses': typeof C3WarehousesRoute
  '/c4/about': typeof C4AboutRoute
  '/c4/contact': typeof C4ContactRoute
  '/c4/events': typeof C4EventsRouteWithChildren
  '/c4/journey': typeof C4JourneyRoute
  '/c4/network': typeof C4NetworkRoute
  '/c4/news': typeof C4NewsRouteWithChildren
  '/c4/offices': typeof C4OfficesRoute
  '/c4/team': typeof C4TeamRoute
  '/c4/verticals': typeof C4VerticalsRoute
  '/c4/warehouses': typeof C4WarehousesRoute
  '/c1/': typeof C1IndexRoute
  '/c2/': typeof C2IndexRoute
  '/c3/': typeof C3IndexRoute
  '/c4/': typeof C4IndexRoute
  '/c1/events/$slug': typeof C1EventsSlugRoute
  '/c1/news/$slug': typeof C1NewsSlugRoute
  '/c2/events/$slug': typeof C2EventsSlugRoute
  '/c2/news/$slug': typeof C2NewsSlugRoute
  '/c3/events/$slug': typeof C3EventsSlugRoute
  '/c3/news/$slug': typeof C3NewsSlugRoute
  '/c3/verticals/$slug': typeof C3VerticalsSlugRoute
  '/c4/events/$slug': typeof C4EventsSlugRoute
  '/c4/news/$slug': typeof C4NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c1'
    | '/c2'
    | '/c3'
    | '/c4'
    | '/sitemap.xml'
    | '/c1/about'
    | '/c1/contact'
    | '/c1/events'
    | '/c1/journey'
    | '/c1/network'
    | '/c1/news'
    | '/c1/offices'
    | '/c1/team'
    | '/c1/verticals'
    | '/c1/warehouses'
    | '/c2/about'
    | '/c2/contact'
    | '/c2/events'
    | '/c2/journey'
    | '/c2/network'
    | '/c2/news'
    | '/c2/offices'
    | '/c2/team'
    | '/c2/verticals'
    | '/c2/warehouses'
    | '/c3/about'
    | '/c3/contact'
    | '/c3/events'
    | '/c3/journey'
    | '/c3/network'
    | '/c3/news'
    | '/c3/offices'
    | '/c3/team'
    | '/c3/verticals'
    | '/c3/warehouses'
    | '/c4/about'
    | '/c4/contact'
    | '/c4/events'
    | '/c4/journey'
    | '/c4/network'
    | '/c4/news'
    | '/c4/offices'
    | '/c4/team'
    | '/c4/verticals'
    | '/c4/warehouses'
    | '/c1/'
    | '/c2/'
    | '/c3/'
    | '/c4/'
    | '/c1/events/$slug'
    | '/c1/news/$slug'
    | '/c2/events/$slug'
    | '/c2/news/$slug'
    | '/c3/events/$slug'
    | '/c3/news/$slug'
    | '/c3/verticals/$slug'
    | '/c4/events/$slug'
    | '/c4/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/c1/about'
    | '/c1/contact'
    | '/c1/events'
    | '/c1/journey'
    | '/c1/network'
    | '/c1/news'
    | '/c1/offices'
    | '/c1/team'
    | '/c1/verticals'
    | '/c1/warehouses'
    | '/c2/about'
    | '/c2/contact'
    | '/c2/events'
    | '/c2/journey'
    | '/c2/network'
    | '/c2/news'
    | '/c2/offices'
    | '/c2/team'
    | '/c2/verticals'
    | '/c2/warehouses'
    | '/c3/about'
    | '/c3/contact'
    | '/c3/events'
    | '/c3/journey'
    | '/c3/network'
    | '/c3/news'
    | '/c3/offices'
    | '/c3/team'
    | '/c3/verticals'
    | '/c3/warehouses'
    | '/c4/about'
    | '/c4/contact'
    | '/c4/events'
    | '/c4/journey'
    | '/c4/network'
    | '/c4/news'
    | '/c4/offices'
    | '/c4/team'
    | '/c4/verticals'
    | '/c4/warehouses'
    | '/c1'
    | '/c2'
    | '/c3'
    | '/c4'
    | '/c1/events/$slug'
    | '/c1/news/$slug'
    | '/c2/events/$slug'
    | '/c2/news/$slug'
    | '/c3/events/$slug'
    | '/c3/news/$slug'
    | '/c3/verticals/$slug'
    | '/c4/events/$slug'
    | '/c4/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/c1'
    | '/c2'
    | '/c3'
    | '/c4'
    | '/sitemap.xml'
    | '/c1/about'
    | '/c1/contact'
    | '/c1/events'
    | '/c1/journey'
    | '/c1/network'
    | '/c1/news'
    | '/c1/offices'
    | '/c1/team'
    | '/c1/verticals'
    | '/c1/warehouses'
    | '/c2/about'
    | '/c2/contact'
    | '/c2/events'
    | '/c2/journey'
    | '/c2/network'
    | '/c2/news'
    | '/c2/offices'
    | '/c2/team'
    | '/c2/verticals'
    | '/c2/warehouses'
    | '/c3/about'
    | '/c3/contact'
    | '/c3/events'
    | '/c3/journey'
    | '/c3/network'
    | '/c3/news'
    | '/c3/offices'
    | '/c3/team'
    | '/c3/verticals'
    | '/c3/warehouses'
    | '/c4/about'
    | '/c4/contact'
    | '/c4/events'
    | '/c4/journey'
    | '/c4/network'
    | '/c4/news'
    | '/c4/offices'
    | '/c4/team'
    | '/c4/verticals'
    | '/c4/warehouses'
    | '/c1/'
    | '/c2/'
    | '/c3/'
    | '/c4/'
    | '/c1/events/$slug'
    | '/c1/news/$slug'
    | '/c2/events/$slug'
    | '/c2/news/$slug'
    | '/c3/events/$slug'
    | '/c3/news/$slug'
    | '/c3/verticals/$slug'
    | '/c4/events/$slug'
    | '/c4/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  C1Route: typeof C1RouteWithChildren
  C2Route: typeof C2RouteWithChildren
  C3Route: typeof C3RouteWithChildren
  C4Route: typeof C4RouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c4': {
      id: '/c4'
      path: '/c4'
      fullPath: '/c4'
      preLoaderRoute: typeof C4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c3': {
      id: '/c3'
      path: '/c3'
      fullPath: '/c3'
      preLoaderRoute: typeof C3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2': {
      id: '/c2'
      path: '/c2'
      fullPath: '/c2'
      preLoaderRoute: typeof C2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c1': {
      id: '/c1'
      path: '/c1'
      fullPath: '/c1'
      preLoaderRoute: typeof C1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c4/': {
      id: '/c4/'
      path: '/'
      fullPath: '/c4/'
      preLoaderRoute: typeof C4IndexRouteImport
      parentRoute: typeof C4Route
    }
    '/c3/': {
      id: '/c3/'
      path: '/'
      fullPath: '/c3/'
      preLoaderRoute: typeof C3IndexRouteImport
      parentRoute: typeof C3Route
    }
    '/c2/': {
      id: '/c2/'
      path: '/'
      fullPath: '/c2/'
      preLoaderRoute: typeof C2IndexRouteImport
      parentRoute: typeof C2Route
    }
    '/c1/': {
      id: '/c1/'
      path: '/'
      fullPath: '/c1/'
      preLoaderRoute: typeof C1IndexRouteImport
      parentRoute: typeof C1Route
    }
    '/c4/warehouses': {
      id: '/c4/warehouses'
      path: '/warehouses'
      fullPath: '/c4/warehouses'
      preLoaderRoute: typeof C4WarehousesRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/verticals': {
      id: '/c4/verticals'
      path: '/verticals'
      fullPath: '/c4/verticals'
      preLoaderRoute: typeof C4VerticalsRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/team': {
      id: '/c4/team'
      path: '/team'
      fullPath: '/c4/team'
      preLoaderRoute: typeof C4TeamRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/offices': {
      id: '/c4/offices'
      path: '/offices'
      fullPath: '/c4/offices'
      preLoaderRoute: typeof C4OfficesRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/news': {
      id: '/c4/news'
      path: '/news'
      fullPath: '/c4/news'
      preLoaderRoute: typeof C4NewsRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/network': {
      id: '/c4/network'
      path: '/network'
      fullPath: '/c4/network'
      preLoaderRoute: typeof C4NetworkRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/journey': {
      id: '/c4/journey'
      path: '/journey'
      fullPath: '/c4/journey'
      preLoaderRoute: typeof C4JourneyRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/events': {
      id: '/c4/events'
      path: '/events'
      fullPath: '/c4/events'
      preLoaderRoute: typeof C4EventsRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/contact': {
      id: '/c4/contact'
      path: '/contact'
      fullPath: '/c4/contact'
      preLoaderRoute: typeof C4ContactRouteImport
      parentRoute: typeof C4Route
    }
    '/c4/about': {
      id: '/c4/about'
      path: '/about'
      fullPath: '/c4/about'
      preLoaderRoute: typeof C4AboutRouteImport
      parentRoute: typeof C4Route
    }
    '/c3/warehouses': {
      id: '/c3/warehouses'
      path: '/warehouses'
      fullPath: '/c3/warehouses'
      preLoaderRoute: typeof C3WarehousesRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/verticals': {
      id: '/c3/verticals'
      path: '/verticals'
      fullPath: '/c3/verticals'
      preLoaderRoute: typeof C3VerticalsRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/team': {
      id: '/c3/team'
      path: '/team'
      fullPath: '/c3/team'
      preLoaderRoute: typeof C3TeamRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/offices': {
      id: '/c3/offices'
      path: '/offices'
      fullPath: '/c3/offices'
      preLoaderRoute: typeof C3OfficesRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/news': {
      id: '/c3/news'
      path: '/news'
      fullPath: '/c3/news'
      preLoaderRoute: typeof C3NewsRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/network': {
      id: '/c3/network'
      path: '/network'
      fullPath: '/c3/network'
      preLoaderRoute: typeof C3NetworkRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/journey': {
      id: '/c3/journey'
      path: '/journey'
      fullPath: '/c3/journey'
      preLoaderRoute: typeof C3JourneyRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/events': {
      id: '/c3/events'
      path: '/events'
      fullPath: '/c3/events'
      preLoaderRoute: typeof C3EventsRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/contact': {
      id: '/c3/contact'
      path: '/contact'
      fullPath: '/c3/contact'
      preLoaderRoute: typeof C3ContactRouteImport
      parentRoute: typeof C3Route
    }
    '/c3/about': {
      id: '/c3/about'
      path: '/about'
      fullPath: '/c3/about'
      preLoaderRoute: typeof C3AboutRouteImport
      parentRoute: typeof C3Route
    }
    '/c2/warehouses': {
      id: '/c2/warehouses'
      path: '/warehouses'
      fullPath: '/c2/warehouses'
      preLoaderRoute: typeof C2WarehousesRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/verticals': {
      id: '/c2/verticals'
      path: '/verticals'
      fullPath: '/c2/verticals'
      preLoaderRoute: typeof C2VerticalsRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/team': {
      id: '/c2/team'
      path: '/team'
      fullPath: '/c2/team'
      preLoaderRoute: typeof C2TeamRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/offices': {
      id: '/c2/offices'
      path: '/offices'
      fullPath: '/c2/offices'
      preLoaderRoute: typeof C2OfficesRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/news': {
      id: '/c2/news'
      path: '/news'
      fullPath: '/c2/news'
      preLoaderRoute: typeof C2NewsRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/network': {
      id: '/c2/network'
      path: '/network'
      fullPath: '/c2/network'
      preLoaderRoute: typeof C2NetworkRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/journey': {
      id: '/c2/journey'
      path: '/journey'
      fullPath: '/c2/journey'
      preLoaderRoute: typeof C2JourneyRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/events': {
      id: '/c2/events'
      path: '/events'
      fullPath: '/c2/events'
      preLoaderRoute: typeof C2EventsRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/contact': {
      id: '/c2/contact'
      path: '/contact'
      fullPath: '/c2/contact'
      preLoaderRoute: typeof C2ContactRouteImport
      parentRoute: typeof C2Route
    }
    '/c2/about': {
      id: '/c2/about'
      path: '/about'
      fullPath: '/c2/about'
      preLoaderRoute: typeof C2AboutRouteImport
      parentRoute: typeof C2Route
    }
    '/c1/warehouses': {
      id: '/c1/warehouses'
      path: '/warehouses'
      fullPath: '/c1/warehouses'
      preLoaderRoute: typeof C1WarehousesRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/verticals': {
      id: '/c1/verticals'
      path: '/verticals'
      fullPath: '/c1/verticals'
      preLoaderRoute: typeof C1VerticalsRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/team': {
      id: '/c1/team'
      path: '/team'
      fullPath: '/c1/team'
      preLoaderRoute: typeof C1TeamRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/offices': {
      id: '/c1/offices'
      path: '/offices'
      fullPath: '/c1/offices'
      preLoaderRoute: typeof C1OfficesRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/news': {
      id: '/c1/news'
      path: '/news'
      fullPath: '/c1/news'
      preLoaderRoute: typeof C1NewsRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/network': {
      id: '/c1/network'
      path: '/network'
      fullPath: '/c1/network'
      preLoaderRoute: typeof C1NetworkRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/journey': {
      id: '/c1/journey'
      path: '/journey'
      fullPath: '/c1/journey'
      preLoaderRoute: typeof C1JourneyRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/events': {
      id: '/c1/events'
      path: '/events'
      fullPath: '/c1/events'
      preLoaderRoute: typeof C1EventsRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/contact': {
      id: '/c1/contact'
      path: '/contact'
      fullPath: '/c1/contact'
      preLoaderRoute: typeof C1ContactRouteImport
      parentRoute: typeof C1Route
    }
    '/c1/about': {
      id: '/c1/about'
      path: '/about'
      fullPath: '/c1/about'
      preLoaderRoute: typeof C1AboutRouteImport
      parentRoute: typeof C1Route
    }
    '/c4/news/$slug': {
      id: '/c4/news/$slug'
      path: '/$slug'
      fullPath: '/c4/news/$slug'
      preLoaderRoute: typeof C4NewsSlugRouteImport
      parentRoute: typeof C4NewsRoute
    }
    '/c4/events/$slug': {
      id: '/c4/events/$slug'
      path: '/$slug'
      fullPath: '/c4/events/$slug'
      preLoaderRoute: typeof C4EventsSlugRouteImport
      parentRoute: typeof C4EventsRoute
    }
    '/c3/verticals/$slug': {
      id: '/c3/verticals/$slug'
      path: '/$slug'
      fullPath: '/c3/verticals/$slug'
      preLoaderRoute: typeof C3VerticalsSlugRouteImport
      parentRoute: typeof C3VerticalsRoute
    }
    '/c3/news/$slug': {
      id: '/c3/news/$slug'
      path: '/$slug'
      fullPath: '/c3/news/$slug'
      preLoaderRoute: typeof C3NewsSlugRouteImport
      parentRoute: typeof C3NewsRoute
    }
    '/c3/events/$slug': {
      id: '/c3/events/$slug'
      path: '/$slug'
      fullPath: '/c3/events/$slug'
      preLoaderRoute: typeof C3EventsSlugRouteImport
      parentRoute: typeof C3EventsRoute
    }
    '/c2/news/$slug': {
      id: '/c2/news/$slug'
      path: '/$slug'
      fullPath: '/c2/news/$slug'
      preLoaderRoute: typeof C2NewsSlugRouteImport
      parentRoute: typeof C2NewsRoute
    }
    '/c2/events/$slug': {
      id: '/c2/events/$slug'
      path: '/$slug'
      fullPath: '/c2/events/$slug'
      preLoaderRoute: typeof C2EventsSlugRouteImport
      parentRoute: typeof C2EventsRoute
    }
    '/c1/news/$slug': {
      id: '/c1/news/$slug'
      path: '/$slug'
      fullPath: '/c1/news/$slug'
      preLoaderRoute: typeof C1NewsSlugRouteImport
      parentRoute: typeof C1NewsRoute
    }
    '/c1/events/$slug': {
      id: '/c1/events/$slug'
      path: '/$slug'
      fullPath: '/c1/events/$slug'
      preLoaderRoute: typeof C1EventsSlugRouteImport
      parentRoute: typeof C1EventsRoute
    }
  }
}

interface C1EventsRouteChildren {
  C1EventsSlugRoute: typeof C1EventsSlugRoute
}

const C1EventsRouteChildren: C1EventsRouteChildren = {
  C1EventsSlugRoute: C1EventsSlugRoute,
}

const C1EventsRouteWithChildren = C1EventsRoute._addFileChildren(
  C1EventsRouteChildren,
)

interface C1NewsRouteChildren {
  C1NewsSlugRoute: typeof C1NewsSlugRoute
}

const C1NewsRouteChildren: C1NewsRouteChildren = {
  C1NewsSlugRoute: C1NewsSlugRoute,
}

const C1NewsRouteWithChildren =
  C1NewsRoute._addFileChildren(C1NewsRouteChildren)

interface C1RouteChildren {
  C1AboutRoute: typeof C1AboutRoute
  C1ContactRoute: typeof C1ContactRoute
  C1EventsRoute: typeof C1EventsRouteWithChildren
  C1JourneyRoute: typeof C1JourneyRoute
  C1NetworkRoute: typeof C1NetworkRoute
  C1NewsRoute: typeof C1NewsRouteWithChildren
  C1OfficesRoute: typeof C1OfficesRoute
  C1TeamRoute: typeof C1TeamRoute
  C1VerticalsRoute: typeof C1VerticalsRoute
  C1WarehousesRoute: typeof C1WarehousesRoute
  C1IndexRoute: typeof C1IndexRoute
}

const C1RouteChildren: C1RouteChildren = {
  C1AboutRoute: C1AboutRoute,
  C1ContactRoute: C1ContactRoute,
  C1EventsRoute: C1EventsRouteWithChildren,
  C1JourneyRoute: C1JourneyRoute,
  C1NetworkRoute: C1NetworkRoute,
  C1NewsRoute: C1NewsRouteWithChildren,
  C1OfficesRoute: C1OfficesRoute,
  C1TeamRoute: C1TeamRoute,
  C1VerticalsRoute: C1VerticalsRoute,
  C1WarehousesRoute: C1WarehousesRoute,
  C1IndexRoute: C1IndexRoute,
}

const C1RouteWithChildren = C1Route._addFileChildren(C1RouteChildren)

interface C2EventsRouteChildren {
  C2EventsSlugRoute: typeof C2EventsSlugRoute
}

const C2EventsRouteChildren: C2EventsRouteChildren = {
  C2EventsSlugRoute: C2EventsSlugRoute,
}

const C2EventsRouteWithChildren = C2EventsRoute._addFileChildren(
  C2EventsRouteChildren,
)

interface C2NewsRouteChildren {
  C2NewsSlugRoute: typeof C2NewsSlugRoute
}

const C2NewsRouteChildren: C2NewsRouteChildren = {
  C2NewsSlugRoute: C2NewsSlugRoute,
}

const C2NewsRouteWithChildren =
  C2NewsRoute._addFileChildren(C2NewsRouteChildren)

interface C2RouteChildren {
  C2AboutRoute: typeof C2AboutRoute
  C2ContactRoute: typeof C2ContactRoute
  C2EventsRoute: typeof C2EventsRouteWithChildren
  C2JourneyRoute: typeof C2JourneyRoute
  C2NetworkRoute: typeof C2NetworkRoute
  C2NewsRoute: typeof C2NewsRouteWithChildren
  C2OfficesRoute: typeof C2OfficesRoute
  C2TeamRoute: typeof C2TeamRoute
  C2VerticalsRoute: typeof C2VerticalsRoute
  C2WarehousesRoute: typeof C2WarehousesRoute
  C2IndexRoute: typeof C2IndexRoute
}

const C2RouteChildren: C2RouteChildren = {
  C2AboutRoute: C2AboutRoute,
  C2ContactRoute: C2ContactRoute,
  C2EventsRoute: C2EventsRouteWithChildren,
  C2JourneyRoute: C2JourneyRoute,
  C2NetworkRoute: C2NetworkRoute,
  C2NewsRoute: C2NewsRouteWithChildren,
  C2OfficesRoute: C2OfficesRoute,
  C2TeamRoute: C2TeamRoute,
  C2VerticalsRoute: C2VerticalsRoute,
  C2WarehousesRoute: C2WarehousesRoute,
  C2IndexRoute: C2IndexRoute,
}

const C2RouteWithChildren = C2Route._addFileChildren(C2RouteChildren)

interface C3EventsRouteChildren {
  C3EventsSlugRoute: typeof C3EventsSlugRoute
}

const C3EventsRouteChildren: C3EventsRouteChildren = {
  C3EventsSlugRoute: C3EventsSlugRoute,
}

const C3EventsRouteWithChildren = C3EventsRoute._addFileChildren(
  C3EventsRouteChildren,
)

interface C3NewsRouteChildren {
  C3NewsSlugRoute: typeof C3NewsSlugRoute
}

const C3NewsRouteChildren: C3NewsRouteChildren = {
  C3NewsSlugRoute: C3NewsSlugRoute,
}

const C3NewsRouteWithChildren =
  C3NewsRoute._addFileChildren(C3NewsRouteChildren)

interface C3VerticalsRouteChildren {
  C3VerticalsSlugRoute: typeof C3VerticalsSlugRoute
}

const C3VerticalsRouteChildren: C3VerticalsRouteChildren = {
  C3VerticalsSlugRoute: C3VerticalsSlugRoute,
}

const C3VerticalsRouteWithChildren = C3VerticalsRoute._addFileChildren(
  C3VerticalsRouteChildren,
)

interface C3RouteChildren {
  C3AboutRoute: typeof C3AboutRoute
  C3ContactRoute: typeof C3ContactRoute
  C3EventsRoute: typeof C3EventsRouteWithChildren
  C3JourneyRoute: typeof C3JourneyRoute
  C3NetworkRoute: typeof C3NetworkRoute
  C3NewsRoute: typeof C3NewsRouteWithChildren
  C3OfficesRoute: typeof C3OfficesRoute
  C3TeamRoute: typeof C3TeamRoute
  C3VerticalsRoute: typeof C3VerticalsRouteWithChildren
  C3WarehousesRoute: typeof C3WarehousesRoute
  C3IndexRoute: typeof C3IndexRoute
}

const C3RouteChildren: C3RouteChildren = {
  C3AboutRoute: C3AboutRoute,
  C3ContactRoute: C3ContactRoute,
  C3EventsRoute: C3EventsRouteWithChildren,
  C3JourneyRoute: C3JourneyRoute,
  C3NetworkRoute: C3NetworkRoute,
  C3NewsRoute: C3NewsRouteWithChildren,
  C3OfficesRoute: C3OfficesRoute,
  C3TeamRoute: C3TeamRoute,
  C3VerticalsRoute: C3VerticalsRouteWithChildren,
  C3WarehousesRoute: C3WarehousesRoute,
  C3IndexRoute: C3IndexRoute,
}

const C3RouteWithChildren = C3Route._addFileChildren(C3RouteChildren)

interface C4EventsRouteChildren {
  C4EventsSlugRoute: typeof C4EventsSlugRoute
}

const C4EventsRouteChildren: C4EventsRouteChildren = {
  C4EventsSlugRoute: C4EventsSlugRoute,
}

const C4EventsRouteWithChildren = C4EventsRoute._addFileChildren(
  C4EventsRouteChildren,
)

interface C4NewsRouteChildren {
  C4NewsSlugRoute: typeof C4NewsSlugRoute
}

const C4NewsRouteChildren: C4NewsRouteChildren = {
  C4NewsSlugRoute: C4NewsSlugRoute,
}

const C4NewsRouteWithChildren =
  C4NewsRoute._addFileChildren(C4NewsRouteChildren)

interface C4RouteChildren {
  C4AboutRoute: typeof C4AboutRoute
  C4ContactRoute: typeof C4ContactRoute
  C4EventsRoute: typeof C4EventsRouteWithChildren
  C4JourneyRoute: typeof C4JourneyRoute
  C4NetworkRoute: typeof C4NetworkRoute
  C4NewsRoute: typeof C4NewsRouteWithChildren
  C4OfficesRoute: typeof C4OfficesRoute
  C4TeamRoute: typeof C4TeamRoute
  C4VerticalsRoute: typeof C4VerticalsRoute
  C4WarehousesRoute: typeof C4WarehousesRoute
  C4IndexRoute: typeof C4IndexRoute
}

const C4RouteChildren: C4RouteChildren = {
  C4AboutRoute: C4AboutRoute,
  C4ContactRoute: C4ContactRoute,
  C4EventsRoute: C4EventsRouteWithChildren,
  C4JourneyRoute: C4JourneyRoute,
  C4NetworkRoute: C4NetworkRoute,
  C4NewsRoute: C4NewsRouteWithChildren,
  C4OfficesRoute: C4OfficesRoute,
  C4TeamRoute: C4TeamRoute,
  C4VerticalsRoute: C4VerticalsRoute,
  C4WarehousesRoute: C4WarehousesRoute,
  C4IndexRoute: C4IndexRoute,
}

const C4RouteWithChildren = C4Route._addFileChildren(C4RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  C1Route: C1RouteWithChildren,
  C2Route: C2RouteWithChildren,
  C3Route: C3RouteWithChildren,
  C4Route: C4RouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
